### ISSUE TITLE
64-bit build produces runtime errors

### ISSUE THREAD

**Issue by peabee** [01micko/pup-volume-monitor#4]
New 64-bit pet version of p-v-m-0.1.17 built...

however
this causes pcmanfm to crash completely (produces no errors when run in terminal or in dmesg)
and in bootsysinit.log I see:
(pup-volume-monitor:6199): GLib-GObject-WARNING **: 10:12:56.960: specified instance size for type 'PupServerMonitor' is smaller than the parent type's 'PupVMMonitor' instance size
(pup-volume-monitor:6199): GLib-CRITICAL **: 10:12:56.961: g_once_init_leave: assertion 'result != 0' failed

**Comment by wdlkmpx** [comment]
DISTRO_NAME='LxPupSc64'
DISTRO_VERSION=18.06

It does show sdb1 (ntfs) (hd). and sdc1 (ntfs-usbflash)
Does not show the bootdrv (iso9960-usbflash)

However i can't compile the latest revision, gcc is missing.. i create a symlink to gcc-7.3.0 .. this is done by a package template.. i wonder what went wrong. And now i see

configure:3305: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:3316: $? = 1
configure:3305: gcc -qversion >&5

I'm booting from usb testing my dir2iso script (supports all variants of woofce isos, also fatdog isos). i replaced light with firefox, and added devx to the iso, nothing else.. by the way adding the devx as a xdrv produces a broken desktop, works but no icons

I'll investigate why this happens one of these days, but how did you manage to compile it

**Comment by wdlkmpx** [comment]
DISTRO_NAME='LxPupSc64'
DISTRO_VERSION=18.06+7

Now i get this error.. 

libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
threads.c: loadable library and perl binaries are mismatched (got handshake key 0xde00080, needed 0xce00080)
HiRes.c: loadable library and perl binaries are mismatched (got handshake key 0xde00080, needed 0xce00080)
HiRes.c: loadable library and perl binaries are mismatched (got handshake key 0xde00080, needed 0xce00080)
threads.c: loadable library and perl binaries are mismatched (got handshake key 0xde00080, needed 0xce00080)

It seems to me that something is wrong and somehow it's also affecting stuff.. i'll test the pet pkg and see how it crashes the desktop, but this system requires some work. You should build a lxpupsc64 iso from testing, maybe there's some fix there. 

That's it for now

**Comment by wdlkmpx** [comment]
Hmm nothing happened, pcmanfm seems to work as expected, partitions are properly listed, hmmm

**Comment by peabee** [comment]
Apologies - my bad - pet was malformed - /usr/lib instead of /usr/lib64 - a new woof-ce build with the fixed pet works fine.
Sorry to have wasted effort....!!
